version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.44
    working_directory: ~/project
    steps:
      # install git
      - run: apk update && apk add git
      # checkout the repository
      - checkout
      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      - run:
          name: Install node 
          command: apk add --update nodejs nodejs-npm
      - run: 
          name: Install NPM dependency
          command: npm install
      - run: 
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run: 
          name: Run build-sass
          command: npm run build-sass
      - run:
          name: Build hugo
          command: hugo --baseURL "https://docs.monaca.io/"
      - save_cache:
          key: docs-{{ epoch }}
          paths:
            - ~/project/public

  deploy-stg:
    machine: true
    working_directory: ~/project
    steps:
      - restore_cache:
          keys:
            - docs
      - run:
          name: Deploy to stg 
          command: aws s3 sync ~/project/public s3://s.docs.monaca.io --delete

  deploy-prod:
    machine: true
    working_directory: ~/project
    steps:
      - restore_cache:
          keys:
            - docs
      - run:
          name: Deploy to production
          command: aws s3 sync ~/project/public s3://docs.monaca.io --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-stg:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build 
          filters:
            branches:
              only: production
